##### BEGIN image/Dockerfile/header-instructions #####
FROM vcwebio/conteco.external.streamsets-libs:elasticsearch_5-lib-3.10.1 AS elastic
FROM vcwebio/conteco.external.streamsets-libs:kafka_2_0-lib-3.10.1 AS kafka
##### END image/Dockerfile/header-instructions #####

##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.streamsets:3.10.1 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/git-repository/*
COPY ./ /conteco/git-repository/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/docker-entrypoint.sh"
COPY ./conteco/configs/etc/sdc/sdc.properties /etc/sdc/sdc.properties
CMD ["/docker-entrypoint.sh", "dc"]
COPY --from=elastic /opt/streamsets-datacollector-3.10.1/streamsets-libs/streamsets-datacollector-elasticsearch_5-lib /opt/streamsets-datacollector-3.10.1/streamsets-libs/streamsets-datacollector-elasticsearch_5-lib
COPY --from=kafka /opt/streamsets-datacollector-3.10.1/streamsets-libs/streamsets-datacollector-apache-kafka_2_0-lib /opt/streamsets-datacollector-3.10.1/streamsets-libs/streamsets-datacollector-apache-kafka_2_0-lib
USER sdc
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="streamsets" \
    CONTECO_NAME="base" \
    CONTECO_TAG="3.10.1" \
    CONTECO_BASE="external.streamsets:3.10.1" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="streamsets" \
      io.vcweb.name="base" \
      io.vcweb.tag="3.10.1" \
      io.vcweb.base="external.streamsets:3.10.1" \
      io.vcweb.build="image-base" \
      io.vcweb.label="streamsets.base - ContEco" \
      io.vcweb.description="Streamsets Base image with configuration changes and pre-installed stage libraries." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.streamsets.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
