#!/usr/bin/env bash

export CONTECO_LABEL="streamsets.base - ContEco"
export CONTECO_DESCRIPTION="Streamsets Base image with configuration changes."

export CONTECO_TYPE="streamsets"
export CONTECO_NAME="base"
export CONTECO_TAG="3.10.1"

export CONTECO_BASE="external.streamsets:3.10.1"
export CONTECO_BUILD="image-base"
