#!/usr/bin/env bash

export CONTECO_LABEL="streamsets.base - ContEco"
export CONTECO_DESCRIPTION="Streamsets Base image with configuration changes and pre-installed stage libraries."

export CONTECO_TYPE="streamsets"
export CONTECO_NAME="base"
export CONTECO_TAG="3.19.0"

export CONTECO_BASE="external.streamsets:3.19.0"
export CONTECO_BUILD="image-base"
