---
version: '3'
services:

# START SERVICE streamsets.base
  streamsets:
    image: ${CONTECO_REGISTRY}vcwebio/conteco.external.streamsets:3.19.0 
    environment: ['SDC_JAVA_OPTS=-Xmx${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xms${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}', 'SDC_CONF_HTTP_BINDHOST=0.0.0.0', 'SDC_CONF_HTTP_ENABLE_FORWARDED_REQUESTS=true', 'SDC_CONF_HTTP_AUTHENTICATION=none', 'SDC_CONF_BUNDLE_UPLOAD_ENABLED=false']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_streamsets_volume:/data']
    ports: [18630:18630]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTECO_DC_STREAMSETS_COMPOSE_EXTENSIONS}
# END SERVICE streamsets.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_streamsets_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
