---
version: '3'
services:

# START SERVICE streamsets.base
  streamsets:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.streamsets.base:3.10.1
    environment: ['SDC_JAVA_OPTS=-Xmx${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xms${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'] 
    command: []
    volumes: []
    ports: [${CONTECO_DC_STREAMSETS_PORTS}]
    networks: [${CONTECO_DC_STREAMSETS_NETWORKS}]
    deploy:
      mode: replicated
      replicas: 1
      resources: 
        limits: 
          cpus: '${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
# END SERVICE streamsets.base

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
