---
version: '3'
services:

# START SERVICE streamsets.base
  streamsets:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.streamsets.base:3.10.1
    environment: ['SDC_JAVA_OPTS=-Xmx${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xms${CONTECO_DC_STREAMSETS_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'] 
    command: [${CONTECO_DC_STREAMSETS_COMMAND}]
    volumes: [${CONTECO_DC_STREAMSETS_VOLUMES}]
    ports: [${CONTECO_DC_STREAMSETS_PORTS}]
    networks: [${CONTECO_DC_STREAMSETS_NETWORKS}]
    deploy: {${CONTECO_DC_STREAMSETS_DEPLOY}}
# END SERVICE streamsets.base

networks:
  ${CONTECO_DC_STREAMSETS_NETWORKS}:
    external: true
